### ISSUE TITLE
Subscribe stream event not working 

### ISSUE THREAD

**Issue by melroyvinpinto** [toitware/api#148]
Nodejs subscribe method not working. Events .on('data', ...) is not giving any data. I am publishing through esp32 which is working perfectly. 
Can i get a sample subscribe code for nodejs stream event

**Comment by floitsch** [comment]
There are some Node examples here: https://github.com/toitware/demos/tree/master/api/node/list_devices

I have also written an extension to streamsheets:
- `connect`: https://github.com/eclipse/streamsheets/blob/master/packages/stream/toit/src/ToitConnector.js#L28
- `startListening`: https://github.com/eclipse/streamsheets/blob/master/packages/stream/toit/src/ToitConsumer.js#L39
